### ISSUE TITLE
`flypkg/package-has-summary` signals error in unparseable buffers

### ISSUE THREAD

**Issue by lunaryorn** [purcell/flycheck-package#20]
`flypkg/package-has-summary` unconditionally applies `package-desc-summary` to the return value of `flypkg/package-el-can-parse-buffer`.  However, if `flypkg/package-el-can-parse-buffer` failed to parse the buffer, it does not return a `package-desc` object, but instead the error list created by `flypkg/error`.  Consequently, `flypkg/package-has-summary` signals a type error, which aborts Flycheck.

I didn't submit a PR to fix this issue, because I'm not so sure how you'd like to see it fixed.   I don't really understand the motiviation behind `flypkg/error`. Particuarly, why does it create a list of arguments for `flycheck-error-new-at` first?  Why doesn't it call `flycheck-error-new-at` right away?

**Comment by Fanael** [comment]
>  I don't really understand the motiviation behind `flypkg/error`. Particuarly, why does it create a list of arguments for `flycheck-error-new-at` first?  Why doesn't it call `flycheck-error-new-at` right away?

Because we sometimes call it with the current buffer different from the original one.
Or, closer to truth, because that's was @purcell's initial idea, see c9dac608.

**Comment by purcell** [comment]
> why does it create a list of arguments for flycheck-error-new-at first? Why doesn't it call flycheck-error-new-at right away?

This code is ultimately going to get extracted into a standalone `package-lint.el`, so I wanted to logically separate the errors from flycheck's functions.

**Comment by lunaryorn** [comment]
@purcell Ah, didn't think of that.  Makes sense.

@Fanael Thanks for fixing this issue!

Many thanks for this checker!
