### ISSUE TITLE
Why check only on 'Package-(Version|Requires)' ?

### ISSUE THREAD

**Issue by dotemacs** [purcell/flycheck-package#25]
Hello @purcell 

why is this constraint in place:

> ;; Checks will currently be enabled only if a "Package-Requires:" or
> ;; "Package-Version:" header is present in the file.

I'm asking as I was about the create a PR to check for the header check where the file doesn't start with ';;;', had a look at the code and saw the above quoted constraints. Once I added 'Package-Version', sure enough, flycheck picked up the omission, the lack of ';;;' as the first line.

I'm aware of the purpose of 'Package-(Version|Requires)':
https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

Just wondering what was the reasoning behind the constraint. 

Thank you for your time

**Comment by Fanael** [comment]
Checks are only enabled when Package-Requires or Package-Version is present because we only want to check packages, and the presence of these headers is a decent indicator of whether the file is meant to be a package.

> I'm asking as I was about the create a PR to check for the header check where the file doesn't start with ';;;'

That would be redundant, `checkdoc` (and thus Flycheck's `emacs-lisp-checkdoc`) already checks that.

**Comment by dotemacs** [comment]
> Checks are only enabled when Package-Requires or Package-Version is present because we only want to check packages, and the presence of these headers is a decent indicator of whether the file is meant to be a package.

So I guess the only way to check a package is to add those headers, if they don't exist in a package and run the flycheck. 

It was only after I did that that I got the package flycheck to work correctly.

> That would be redundant, checkdoc (and thus Flycheck's emacs-lisp-checkdoc) already checks that.

Yes, but only by having the above constraints added, as mentioned in my original post above.

It might be a good idea to add a note about this constraint to the README so that it's **super** obvious to anybody else who want to use this package. What do you think?

Thanks

**Comment by Fanael** [comment]
> It might be a good idea to add a note about this constraint to the README so that it's super obvious to anybody else who want to use this package. What do you think?

It's already there, see the second paragraph:

> Currently these checks are only activated if a `Package-Requires` or `Package-Version` header is present in the file, and checks center on the validity of the data in that header.

**Comment by dotemacs** [comment]
> It's already there, see the second paragraph:

>> Currently these checks are only activated if a Package-Requires or Package-Version header is present in the file, and checks center on the validity of the data in that header.

My bad, didn't see it. 

Sorry for the noise and thank you!

**Comment by purcell** [comment]
Yeah, it would be possible to assume that every elisp file is meant to be a package, but most of them aren't, so there'd just be a lot of extra flycheck noise then.
