### ISSUE TITLE
Old version in MELPA stable

### ISSUE THREAD

**Issue by Fanael** [purcell/flycheck-package#3]
The version in MELPA stable doesn't call `(package-lint-looks-like-a-package-p)`, so it runs on all Emacs Lisp buffers.

Easiest fix: tag a new release.

**Comment by purcell** [comment]
Thanks. I've pushed a 0.12 tag, so this should resolve itself when MELPA Stable next builds.

**Comment by Fanael** [comment]
I mean, I lied: it doesn't, because package-lint in MELPA stable is, too, very old. But I just tagged package-lint 0.4, so it *would* break after rebuild 😉

**Comment by purcell** [comment]
Aha, right!
