### ISSUE TITLE
Non-standard keyword check warns on multiple keywords

### ISSUE THREAD

**Issue by Fanael** [purcell/flycheck-package#31]
It doesn't like commas: it warns that "lisp," is not a valid keyword.

**Comment by alphapapa** [comment]
I think this is not correct.  For example, there are `el` files distributed with Emacs that do not use commas, such as `semantic.el`:

```el
;;; semantic.el --- Semantic buffer evaluator.

;; Copyright (C) 1999-2014 Free Software Foundation, Inc.

;; Author: Eric M. Ludlam <zappo@gnu.org>
;; Keywords: syntax tools
;; Version: 2.2

;; This file is part of GNU Emacs.
```

**Comment by Fanael** [comment]
`auto-insert` uses commas, so that's assumed to be correct.

Anyway, that's irrelevant: parsing this list manually is unnecessary, we should use `lm-keyword-list` instead.

**Comment by alphapapa** [comment]
> auto-insert uses commas, so that's assumed to be correct.

I had forgotten about that function, thanks.  However, grepping through the `.el` files in Emacs' source, I see 135 that have multiple keywords without commas separating them, dating back to at least 1990, so it seems like the de facto standard allows both.  It would seem strange to mark files as having errors that have been distributed with Emacs for 26 years.

**Comment by Fanael** [comment]
That's right, and `lm-keywords-list` allows both, so both comma-separated and space-separated keywords are considered correct now.

**Comment by alphapapa** [comment]
Oh, of course.  Thanks.  :)
