### ISSUE TITLE
Change keyword check to warning?

### ISSUE THREAD

**Issue by alphapapa** [purcell/flycheck-package#37]
I noticed today that even a lot of the files distributed with Emacs, including the ones that have been around for decades, have "non-standard" keywords.  Should we change `flycheck-package--check-keywords-list` to give warnings instead of errors?

In the bigger picture, I wonder if we should start a discussion in the community or on the Emacs mailing list about package keywords.  It seems like a shame that only the [RMS-approved keywords](https://github.com/emacs-mirror/emacs/blob/master/lisp/finder.el#L39) are used, even when package authors try to provide more specific ones.  Of course, if every keyword in every package were shown, no matter what, it could get a bit messy...  But maybe there's some kind of happy medium...? What do you all think?

**Comment by Fanael** [comment]
I agree.
