### ISSUE TITLE
Relationship with cask?

### ISSUE THREAD

**Issue by DamienCassou** [purcell/flycheck-package#5]
I'm using `cask` and `flycheck-package` to develop my packages. Everything was great until I started using `borg` for my emacs configuration. Now that I'm using `borg`, my `package-archive-contents` is nil and this makes `package-lint--check-packages-installable` fail and report each dependency of a package as `"non installable"`.

Do you have any recommendation regarding this process?

**Comment by purcell** [comment]
This is a `package-lint` question more than a `flycheck-package` question. If you want to get proper feedback from `package-lint` (including via `flycheck-package`) then you'll simply _need_ to have `package-archive-contents` filled. You can always use something like `(with-eval-after-load 'package-lint (package-initialize))`, but you'll also have to periodically run `package-refresh-contents`.

**Comment by purcell** [comment]
Re. Cask, the same thing applies, btw: you need to initialize the package info before running `package-lint`. You can see how we handle that in our travis build here: https://github.com/purcell/package-lint/blob/master/run-tests.sh

**Comment by DamienCassou** [comment]
I reported an issue on package-lint: https://github.com/purcell/package-lint/issues/73. Now, I think that is the responsibility of`flycheck-package` to avoid making the editor configuration impact the linting results. Shouldn't flycheck-package call an external Emacs (like the `emacs-lisp` checker) instead of using the current one and its configuration?
